# Generated by Django 4.2.6 on 2024-03-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sub_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
