# Generated by Django 4.2.6 on 2024-03-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='sub_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
