# Generated by Django 4.2.6 on 2024-03-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skll',
            new_name='Skill',
        ),
    ]
